name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 💡 Optional: lets you run manually from GitHub Actions tab

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🪄 Create env.js in the root instead of /public
      - name: Create env.js from secrets
        run: |
          cat <<EOF > env.js
          window.__APP_CONFIG__ = {
            FIREBASE_API_KEY: "${{ secrets.FIREBASE_API_KEY }}",
            FIREBASE_DB_URL: "${{ secrets.FIREBASE_DB_URL }}",
            FIREBASE_PROJECT_ID: "${{ secrets.FIREBASE_PROJECT_ID }}"
          };
          EOF

      # 🧪 Optional: debug to confirm file exists
      - name: List files after generating env.js
        run: ls -R

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # deploy everything in repo root

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
