name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # optional: manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Create env.js in the root (next to index.html)
      - name: Create env.js from secrets
        run: |
          cat <<EOF > env.js
          window.__APP_CONFIG__ = {
            FIREBASE_API_KEY: "${{ secrets.FIREBASE_API_KEY }}",
            FIREBASE_DB_URL: "${{ secrets.FIREBASE_DB_URL }}",
            FIREBASE_PROJECT_ID: "${{ secrets.FIREBASE_PROJECT_ID }}"
          };
          EOF

      # 3️⃣ Optional: debug to see all files
      - name: List all files
        run: ls -R

      # 4️⃣ Configure GitHub Pages
      - name: Configure Pages
        uses: actions/configure-pages@v4

      # 5️⃣ Upload all files for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # deploy everything in the root, including env.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 6️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
